version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Fluky/Fluky.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netstandard1.6/publish
  - cmd: dotnet pack ./src/Fluky/Fluky.csproj -o ../../artifacts --include-symbols
after_build:
  # For once the build has completed
artifacts:
 - path: '\artifacts\'
   name: NugetPkg
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/Fluky.Tests/Fluky.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd src/Fluky.Tests
  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off
