version: '2.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master

init:
  - cmd: git config --global core.autocrlf true
  - ps: $env:nugetversion = if ($env:APPVEYOR_REPO_TAG -eq $True) { "$env:APPVEYOR_BUILD_VERSION" } else { "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_REPO_BRANCH" }
  - ps: Update-AppveyorBuild -Version $env:nugetversion

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  disable_publish_on_pr: true

install:
  # Install repo specific stuff here
  
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Fluky/Fluky.csproj --verbosity m
  
build_script:
  # output will be in ./src/bin/debug/netstandard1.6/publish
  - cmd: dotnet pack ./src/Fluky/Fluky.csproj -o ../../artifacts --include-symbols  /p:Version="{nugetversion}"
after_build:
  # For once the build has completed
  
artifacts:
 - path: '\artifacts\*.nupkg'
   name: Nuget
   
clone_depth: 1

test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/Fluky.Tests/Fluky.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd src/Fluky.Tests
  - cmd: dotnet test
  
on_finish :
  # any cleanup in here
  
deploy:
- provider: NuGet
  api_key:
    secure: cACylPTv30jFnQzzCUvDPOpUPdEjvLEYvdG2ueENaLbBEjgoOzHPnnA0NAlBpMnZ
    artifact: '\artifacts\*.nupkg'
